<?php

/**
 * @file
 * Contains video_plupload_widget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function video_plupload_widget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the video_plupload_widget module.
    case 'help.page.video_plupload_widget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a plupload-type upload field to the video content type') . '</p>';
      return $output;

    default:
  }
}
