<?php

/**
 * @file
 * Contains leaflet_alter_markers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function leaflet_alter_markers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the leaflet_alter_markers module.
    case 'help.page.leaflet_alter_markers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('changes markers based on grouping fields in the view') . '</p>';
      return $output;

    default:
  }
}
