<?php

/**
 * @file
 * Hook implementation for the Drulma Menu Item Content Fields module.
 */

use Drupal\drulma_menu_item_fields\Render\Callback;

/**
 * Implements hook_preprocess_menu__bulma_navbar().
 */
function menu_item_fields_preprocess_menu__bulma_navbar(&$variables) {
  menu_item_fields_preprocess_menu__field_content($variables);
  foreach ($variables['items'] as $itemId => &$item) {
    if (isset($item['content'])) {
      $item['content']['#pre_render'][] = [Callback::class, 'preRenderMenuLinkContent'];
      $item['content']['#attached']['library'][] = 'drulma_menu_item_fields/navbar-adjust';
    }
  }
}
