<?php

/**
 * @file
 * Contains image_styles_creator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function image_styles_creator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the image_styles_creator module.
    case 'help.page.image_styles_creator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates image styles before they are required. In this way, image delivery is speeded up.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function image_styles_creator_form_alter(&$form, &$form_state, $form_id)
{

    if ($form_id == 'image_styles_creator_generator_form') {

        $form['actions']['submit']['#value'] = t('Generate image styles');
    }
}
