date_format_exif: null
granularity: 0
update_metadata: false
write_empty_values: false
extraction_solution: php_extensions
exiftool_location: exiftool
vocabulary: '0'
mediatypes: ''
nodetypes:
  photo: photo
  hebergement: '0'
  page: '0'
  photography: '0'
_core:
  default_config_hash: uhJeErYqTWZq5QycHNK-AXD6kU312yXBnG5QsBuL1Ds
