<?php

/**
 * @file
 * Contains image_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function image_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the image_import module.
    case 'help.page.image_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Batch imports images and creates a node for each of them. Extracts EXIF/IPTC values to fill node fields.') . '</p>';
      return $output;

    default:
  }
}
