# Alter schema for the configuration files of the System module.
system.performance:
  mapping:
    minifyhtml:
      type: mapping
      label: 'MinifyHTML performance settings'
      mapping:
        minify_html:
          type: boolean
          label: 'Minified Source HTML'
